input {
    kinesis {
        kinesis_stream_name => "playground-INFRA-aws-account-setup-LoggingKinesisStream6A6267CB-350cGBTV94bT"
        application_name => "CentralElkKclTable-For-Playground"
        role_arn => "arn:aws:iam::702972749545:role/playground-INFRA-aws-acco-CentralElkStackRoleLogsta-xZYyGwnJsKTg"
        region => "eu-west-1"
        initial_position_in_stream => "TRIM_HORIZON"
        client_version_config_2x_compatibility => true
        codec => json { }
    }
}

output {
    stdout { codec => rubydebug }
}
