input {
    kinesis {
        kinesis_stream_name => "placeholder"
        application_name => "KclV2Table"
        role_arn => "placeholder"
        region => "eu-west-1"
        initial_position_in_stream => "TRIM_HORIZON"
        codec => json { }
    }
}

output {
    stdout { codec => rubydebug }
}
