input {
    kinesis {
        kinesis_stream_name => "placeholder" # aws kinesis list-streams --profile <profile> --region eu-west-1  --query "StreamNames[?contains(@, 'Logging')]" --output text
        application_name => "CentralElkKclTable-For-KclPlugin-Test" # The name needs to be in the format `CentralElkKclTable-For-*` to avoid permissions issues in the dynamodb tables. Always use a name different from the production one.
        role_arn => "placeholder" # aws iam list-roles --profile <profile>  --query "Roles[?contains(RoleName, 'Elk')].Arn" --output text
        region => "eu-west-1"
        initial_position_in_stream => "TRIM_HORIZON"
        codec => json { }
    }
}

output {
    stdout { codec => rubydebug }
}
